#
# kernel 2.6 driver Makefile
#

clean : 
	rm -rf *.ko
	rm -rf *.mod.*
	rm -rf .*.cmd
	rm -rf *.o
	rm -rf .tmp_versions
	rm -rf Module.symvers
	rm -rf modules.order
	rm -rf mmc/*.o
	rm -rf mmc/.*.cmd
	rm -rf mmc/*.mod.*
	rm -rf hdmi/*.o
	rm -rf hdmi/.*.cmd
	rm -rf hdmi/*.mod.*

